### ISSUE TITLE
syscall.Dup2() not supported on aarch64

### ISSUE THREAD

**Issue by clandmeter** [ngaut/log#4]
This could possibly be replaced by Dup3:

http://man7.org/linux/man-pages/man2/dup.2.html

ref:https://github.com/alpinelinux/aports/commit/02ad0fb3b81610d2e8c2133507115f88e09f0044

ref:https://github.com/go-gitea/gitea/issues/691

**Comment by AlexKichkailo** [comment]
This is broken again by https://github.com/ngaut/log/commit/f3329cba28a5442757e50215d3768f77d5dcb631
